const fs = require('fs-extra')

fs.copySync('./background.js', './dist/background.js')
fs.copySync('./content.js', './dist/content.js')
fs.copySync('./icon128.png', './dist/icon128.png')
fs.copySync('./manifest.json', './dist/manifest.json')
fs.copySync('./options.html', './dist/options.html')
fs.copySync('./popup.html', './dist/popup.html')
fs.copySync('./popup.js', './dist/popup.js')
fs.copySync('./style.css', './dist/style.css')
fs.copySync('./settings.js', './dist/settings.js')
fs.copySync('./speechmatics.html', './dist/speechmatics.html')
fs.copySync('./deepgram.html', './dist/deepgram.html')
fs.copySync('./soniox.html', './dist/soniox.html')
